import type { User, Listing, Review, Conversation, Message } from './types'

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'mariastyle',
    shopName: 'Maria Style Shop',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=200&fit=crop',
    location: 'Chișinău',
    rating: 4.9,
    reviewCount: 127,
    itemsSold: 89,
    memberSince: '2022-03-15',
    bio: 'Haine de calitate la prețuri accesibile. Livrare rapidă!',
    followers: 1234,
    following: 567,
    isVerified: true,
    plan: 'pro',
    activeListingsCount: 45,
  },
  {
    id: '2',
    username: 'vintagemd',
    shopName: 'Vintage Moldova',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    location: 'Bălți',
    rating: 4.7,
    reviewCount: 85,
    itemsSold: 62,
    memberSince: '2021-09-20',
    bio: 'Piese vintage autentice. Calitate garantată.',
    followers: 892,
    following: 234,
    isVerified: true,
    plan: 'unlimited',
    activeListingsCount: 78,
  },
  {
    id: '3',
    username: 'anachisinau',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    location: 'Chișinău',
    rating: 5.0,
    reviewCount: 43,
    itemsSold: 31,
    memberSince: '2023-01-10',
    bio: 'Vând haine puțin purtate. Totul e verificat.',
    followers: 456,
    following: 123,
    isVerified: false,
    plan: 'starter',
    activeListingsCount: 12,
  },
  {
    id: '4',
    username: 'streetmd',
    shopName: 'Street Wear MD',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
    location: 'Chișinău',
    rating: 4.8,
    reviewCount: 156,
    itemsSold: 203,
    memberSince: '2020-06-01',
    bio: 'Streetwear & sneakers. Nike, Adidas, Supreme.',
    followers: 3421,
    following: 890,
    isVerified: true,
    plan: 'unlimited',
    activeListingsCount: 95,
  },
  {
    id: '5',
    username: 'irinacahul',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop',
    location: 'Cahul',
    rating: 4.6,
    reviewCount: 67,
    itemsSold: 45,
    memberSince: '2022-11-05',
    bio: 'Moda sustenabilă. Dă hainelor o a doua viață!',
    followers: 678,
    following: 345,
    isVerified: false,
    plan: 'starter',
    activeListingsCount: 18,
  },
]

export const currentUser: User = {
  id: 'current',
  username: 'eu',
  shopName: 'Magazinul meu',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
  location: 'Chișinău',
  rating: 4.8,
  reviewCount: 23,
  itemsSold: 15,
  memberSince: '2023-06-01',
  bio: 'Vând haine de calitate.',
  followers: 234,
  following: 456,
  isVerified: true,
  plan: 'free',
  activeListingsCount: 2,
}

export const mockListings: Listing[] = [
  {
    id: '1',
    title: 'Palton Zara din lână - Camel',
    description: 'Palton elegant din amestec de lână de la Zara. Purtat de două ori, în stare perfectă. Croială clasică, guler rever, două buzunare frontale. Perfect pentru toamnă/iarnă.',
    price: 650,
    images: [
      'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=800&fit=crop',
    ],
    category: 'femei',
    size: 'M',
    brand: 'Zara',
    condition: 'foarte_buna',
    color: 'Bej',
    seller: mockUsers[0],
    createdAt: '2024-01-15',
    views: 234,
    favorites: 45,
    location: 'Chișinău',
    isBoosted: true,
  },
  {
    id: '2',
    title: 'Adidas Originals Superstar - Alb/Negru',
    description: 'Sneakers Adidas Superstar clasici. Stare foarte bună, purtați de câteva ori. Mărimea 42.',
    price: 450,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&h=800&fit=crop',
    ],
    category: 'incaltaminte',
    size: '42',
    brand: 'Adidas',
    condition: 'foarte_buna',
    color: 'Alb',
    seller: mockUsers[3],
    createdAt: '2024-01-14',
    views: 189,
    favorites: 67,
    location: 'Chișinău',
  },
  {
    id: '3',
    title: 'Geacă de piele H&M - Neagră',
    description: 'Geacă de piele ecologică H&M. Nou fără etichetă, niciodată purtată. Talie S.',
    price: 380,
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=800&fit=crop',
    ],
    category: 'femei',
    size: 'S',
    brand: 'H&M',
    condition: 'nou_fara_eticheta',
    color: 'Negru',
    seller: mockUsers[2],
    createdAt: '2024-01-13',
    views: 156,
    favorites: 34,
    location: 'Chișinău',
  },
  {
    id: '4',
    title: 'Nike Air Force 1 Low - Alb',
    description: 'Nike Air Force 1 clasici, albi. Mărimea 41. Puțin purtați, stare bună.',
    price: 520,
    images: [
      'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=600&h=800&fit=crop',
    ],
    category: 'incaltaminte',
    size: '41',
    brand: 'Nike',
    condition: 'buna',
    color: 'Alb',
    seller: mockUsers[3],
    createdAt: '2024-01-12',
    views: 312,
    favorites: 89,
    location: 'Chișinău',
    isBoosted: true,
  },
  {
    id: '5',
    title: 'Rochie de vară florală - Mango',
    description: 'Rochie de vară cu print floral de la Mango. Mărimea S. Perfectă pentru ocazii.',
    price: 220,
    images: [
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&h=800&fit=crop',
    ],
    category: 'femei',
    size: 'S',
    brand: 'Mango',
    condition: 'foarte_buna',
    color: 'Multicolor',
    seller: mockUsers[4],
    createdAt: '2024-01-11',
    views: 98,
    favorites: 23,
    location: 'Cahul',
  },
  {
    id: '6',
    title: 'Geacă bărbătească Levi\'s - Denim',
    description: 'Geacă denim Levi\'s vintage. Talie M. Stare excelentă.',
    price: 480,
    images: [
      'https://images.unsplash.com/photo-1544441893-675973e31985?w=600&h=800&fit=crop',
    ],
    category: 'barbati',
    size: 'M',
    brand: 'Levi\'s',
    condition: 'foarte_buna',
    color: 'Albastru',
    seller: mockUsers[1],
    createdAt: '2024-01-10',
    views: 145,
    favorites: 41,
    location: 'Bălți',
  },
  {
    id: '7',
    title: 'Geantă din piele Reserved - Maro',
    description: 'Geantă de damă din piele naturală Reserved. Aproape nouă, folosită de 2 ori.',
    price: 290,
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=800&fit=crop',
    ],
    category: 'accesorii',
    brand: 'Reserved',
    condition: 'foarte_buna',
    color: 'Maro',
    seller: mockUsers[0],
    createdAt: '2024-01-09',
    views: 167,
    favorites: 52,
    location: 'Chișinău',
  },
  {
    id: '8',
    title: 'Viniuri Pink Floyd - colecție',
    description: '3 discuri vinil Pink Floyd în stare excelentă. The Wall, Dark Side, Wish You Were Here.',
    price: 750,
    images: [
      'https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=600&h=800&fit=crop',
    ],
    category: 'colectionabile',
    condition: 'foarte_buna',
    seller: mockUsers[1],
    createdAt: '2024-01-08',
    views: 203,
    favorites: 78,
    location: 'Bălți',
  },
  {
    id: '9',
    title: 'Pantaloni Tommy Hilfiger - Chino Bej',
    description: 'Pantaloni chino Tommy Hilfiger, bej. Mărimea 32/32. Ca noi.',
    price: 310,
    images: [
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&h=800&fit=crop',
    ],
    category: 'barbati',
    size: '32/32',
    brand: 'Tommy Hilfiger',
    condition: 'nou_fara_eticheta',
    color: 'Bej',
    seller: mockUsers[2],
    createdAt: '2024-01-07',
    views: 88,
    favorites: 19,
    location: 'Chișinău',
  },
  {
    id: '10',
    title: 'Vază ceramică handmade - Decor',
    description: 'Vază ceramică handmade, unicat. Perfectă pentru living sau dormitor.',
    price: 180,
    images: [
      'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=600&h=800&fit=crop',
    ],
    category: 'casa-decor',
    condition: 'nou_cu_eticheta',
    color: 'Bej',
    seller: mockUsers[4],
    createdAt: '2024-01-06',
    views: 67,
    favorites: 28,
    location: 'Cahul',
  },
  {
    id: '11',
    title: 'Bluză Calvin Klein - Oversized',
    description: 'Bluză oversized Calvin Klein, neagră. Mărimea L. Nouă cu etichetă.',
    price: 270,
    images: [
      'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=600&h=800&fit=crop',
    ],
    category: 'femei',
    size: 'L',
    brand: 'Calvin Klein',
    condition: 'nou_cu_eticheta',
    color: 'Negru',
    seller: mockUsers[0],
    createdAt: '2024-01-05',
    views: 134,
    favorites: 39,
    location: 'Chișinău',
  },
  {
    id: '12',
    title: 'Cizme Pull&Bear - Maro, măr. 38',
    description: 'Cizme din imitație de piele Pull&Bear. Mărimea 38. Purtate de 3 ori.',
    price: 200,
    images: [
      'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=600&h=800&fit=crop',
    ],
    category: 'incaltaminte',
    size: '38',
    brand: 'Pull & Bear',
    condition: 'buna',
    color: 'Maro',
    seller: mockUsers[2],
    createdAt: '2024-01-04',
    views: 79,
    favorites: 15,
    location: 'Chișinău',
  },
]

export const mockReviews: Review[] = [
  {
    id: '1',
    reviewer: mockUsers[2],
    rating: 5,
    comment: 'Produse de calitate, livrare rapidă. Recomand cu încredere!',
    createdAt: '2024-01-10',
    listingTitle: 'Palton Zara din lână',
  },
  {
    id: '2',
    reviewer: mockUsers[3],
    rating: 5,
    comment: 'Exact cum era descris. Mulțumesc!',
    createdAt: '2023-12-20',
    listingTitle: 'Geantă din piele Reserved',
  },
  {
    id: '3',
    reviewer: mockUsers[4],
    rating: 4,
    comment: 'Bun, dar livrarea a durat un pic mai mult.',
    createdAt: '2023-11-15',
    listingTitle: 'Rochie Mango',
  },
]

